### ISSUE TITLE
Error running example

### ISSUE THREAD

**Issue by justinmoon** [btsecom/api-sample#2]
When I try to run [this example](https://github.com/btsecom/api-sample/blob/master/python/spot/market_order.py) with either real or test endpoints I get the following error:

```
{"errorCode":403,"message":"FORBIDDEN: Nonce specified exceeds current timestamp by more than time window","status":403}
```

**Comment by justinmoon** [comment]
Your docs said that the nonce should be the current timestamp, but the example is multiplying it by 1000.

I tried just passing the current timestamp but that returned the same error.

**Comment by justinmoon** [comment]
If I send a nonce of `0` I get the same error message, which doesn't make sense because 0 doesn't exceed any unix timestamp.

**Comment by justinmoon** [comment]
My computer giving this as the unix time: 1598290819.6369228.

So I don't think it's a problem on my end.

**Comment by thehapax** [comment]
@justinmoon says it works on mac OS but doesn't on linux for some reason. both testnet and production

**Comment by thehapax** [comment]
Fwiw, the only times i've experienced nonce errors with exchanges are: 

- using the API keys too soon after they are created
- network error

Might not be the cause but always worth checking

**Comment by thehapax** [comment]
One other potential source for this error 

> ```
> {"errorCode":403,"message":"FORBIDDEN: Nonce specified exceeds current timestamp by more than time window","status":403}
> ```

is that the computer's local clocks are not synchronized, if on ubuntu, check for global time synchronization with 

```
$ timedatectl
```
or https://ostechnix.com/how-to-set-up-time-synchronization-on-ubuntu/

If on OSX, sync your time by setting date and time automatically with time.apple.com

**Comment by btsedev** [comment]
@thehapax @justinmoon please let us know if the issue still persists
