### ISSUE TITLE
ORDER_REJECTED

### ISSUE THREAD

**Issue by ShieldTrade** [btsecom/api-sample#21]
Please consider the following situation on testnet.

After amending price order is on book still not filled.
`BTSE_ORIGINAL {'topic': 'notificationApiV1', 'id': '', 'data': {'symbol': 'BTCPFC', 'orderID': 'fff9ab70-a50b-4b59-8dae-89e9f08cd506', 'orderMode': 'MODE_BUY', 'orderType': 'TYPE_LIMIT', 'type': '', 'price': 30157.0, 'size': 100.0, 'triggerPrice': 0.0, 'pegPriceDeviation': 1.0, 'stealth': 1.0, 'status': 'AMEND_ORDER', 'timestamp': 1654719835028, 'maker': True, 'remainingSize': 100.0, 'avgFillPrice': 0.0, 'fillSize': 0.0, 'clOrderID': 'test-order-placement', 'originalSize': 100.0, 'time_in_force': 'GTC'}}`

Order gets partially filled.
`BTSE_ORIGINAL {'topic': 'notificationApiV1', 'id': '', 'data': {'symbol': 'BTCPFC', 'orderID': 'fff9ab70-a50b-4b59-8dae-89e9f08cd506', 'orderMode': 'MODE_BUY', 'orderType': 'TYPE_LIMIT', 'type': '', 'price': 30157.0, 'size': 18.0, 'triggerPrice': 0.0, 'pegPriceDeviation': 1.0, 'stealth': 1.0, 'status': 'ORDER_PARTIALLY_TRANSACTED', 'timestamp': 1654719835107, 'maker': True, 'remainingSize': 82.0, 'avgFillPrice': 30157.0, 'fillSize': 18.0, 'clOrderID': 'test-order-placement', 'originalSize': 100.0, 'time_in_force': 'GTC'}}`

Amend price. new price 30133.5. client response does not show any problem with `status 200`
```
<ClientResponse(https://testapi.btse.io/futures/api/v2.1/order) [200 ]>
<CIMultiDictProxy('Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '400', 'Connection': 'keep-alive', 'Date': 'Wed, 08 Jun 2022 20:23:55 GMT', 'Cache-Control': 'no-cache', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 b9ff2ec964f1eea80fc668bb9d85ec54.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'MXP64-C2', 'X-Amz-Cf-Id': '_nSxiPv5s5BlF3YaUY4trfxc2pX6jVwluiv7lulqX7SZKLuzwNMoyw==')>
```

but your notificationApiV1 responds
`BTSE_ORIGINAL {'topic': 'notificationApiV1', 'id': '', 'data': {'symbol': 'BTCPFC', 'orderID': 'fff9ab70-a50b-4b59-8dae-89e9f08cd506', 'orderMode': 'MODE_BUY', 'orderType': '', 'type': '', 'price': 30133.5, 'size': 100.0, 'triggerPrice': 0.0, 'pegPriceDeviation': 1.0, 'stealth': 1.0, 'status': 'ORDER_REJECTED', 'timestamp': 1654719836380, 'maker': False, 'remainingSize': 100.0, 'avgFillPrice': 0.0, 'fillSize': 0.0, 'clOrderID': '', 'originalSize': 100.0, 'time_in_force': 'GTC'}}`

Is there a way to have more info about what caused the order to be rejected?

if at `'timestamp': 1654719835107` I have '`remainingSize': 82.0`, why do I have `'remainingSize': 100.0` at `'timestamp': 1654719836380 `after more then 1200 mls?

Reading your official document [Notifications version 2](https://www.btse.com/apiexplorer/futures/#wsnotifications2) I do not see any `status ORDER_REJECTED`. is that correct ?

Thankyou

**Comment by yuanchenho** [comment]
Hi @ShieldTrade In your case the 2nd amend order 

```
<ClientResponse(https://testapi.btse.io/futures/api/v2.1/order) [200 ]>
<CIMultiDictProxy('Content-Type': 'application/json;charset=UTF-8', 'Content-Length': '400', 'Connection': 'keep-alive', 'Date': 'Wed, 08 Jun 2022 20:23:55 GMT', 'Cache-Control': 'no-cache', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 b9ff2ec964f1eea80fc668bb9d85ec54.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'MXP64-C2', 'X-Amz-Cf-Id': '_nSxiPv5s5BlF3YaUY4trfxc2pX6jVwluiv7lulqX7SZKLuzwNMoyw==')>
```

hit a timeout internally in our matching engine. And reason for returning a payload with `remainingSize: 100` was because we failed to fetch current state of that order so we returned the last successful order payload. 

We will add a new status to better decribe the `amend timeout` behavior
