### ISSUE TITLE
API Key Error when running wallet.py

### ISSUE THREAD

**Issue by thehapax** [btsecom/api-sample#3]
On both testnet and production, the wallet.py errors as follows. The API keys were created with wallet access as shown in the image below.

```{"errorCode":5541,"message":"FORBIDDEN: This operation is not allowed for current API Key","status":403}```

<img width="532" alt="Screen Shot 2020-08-26 at 3 08 54 PM" src="https://user-images.githubusercontent.com/39811582/91493506-4762f100-e86c-11ea-9594-79e43a02a2c0.png">

The rest of the examples are working, however, market orders, limit trades, etc.

**Comment by btsedev** [comment]
For wallet API, it uses the read permission. This information is provided as a tag on the right of each API title

![Screen Shot 2021-05-17 at 13 24 09](https://user-images.githubusercontent.com/42797243/118436346-408a5000-b713-11eb-9f2c-099782e5ccf8.png)

**Comment by yuanchenho** [comment]
hey @thehapax we are going to close this issue for now.
If your problem persists please create another issue and we'll respond there.

Thanks.
